---
- hosts: all
  remote_user: "{{ user_acc }}"
  vars_files:
    - vars.yml

  tasks:
    - name: Announce deploy to the Discord channel
      community.general.discord:
        webhook_id: "980507364417499146"
        webhook_token: "{{ discord_deploy_webhook_token }}"
        content: "Kosa deploy started for {{ inventory_hostname }}"

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
      become: yes

    - name: copy priv key to server
      copy:
        src: "{{ key_dir }}/{{ key_name }}"
        dest: "{{ DEPLOY_KEY_PATH }}"
        owner: "{{ user_acc }}"
        group: "{{ user_acc }}"
        mode: 0600
      become: yes

    - name: copy pub key to server
      copy:
        src: "{{ key_dir }}/{{ key_name }}.pub"
        dest: "{{ DEPLOY_KEY_PATH }}.pub"
        owner: "{{ user_acc }}"
        group: "{{ user_acc }}"
        mode: 0644
      become: yes

    - name: ensure srv directory exists
      file:
        path: "{{ srv_dir }}"
        state: "directory"
        owner: "{{ user_acc }}"
        group: "{{ user_acc }}"
      become: yes

    - name: clone/pull project repo
      tags: code
      git:
        repo: "{{ repo_url }}"
        version: "{{ repo_version }}"
        dest: "{{ repo_dir }}"
        accept_hostkey: yes
        force: yes
        update: yes
        depth: 1
        # key_file: "{{ DEPLOY_KEY_PATH }}"
      notify:
        - app daemon reload
        - app restart
      become: yes
      become_user: "{{ user_acc }}"

    - name: update environment file
      tags: env
      template:
        src: env.conf.j2
        dest: "{{ env_file }}"
      notify:
        - app daemon reload
        - app restart
      become: yes

    - name: Recursively change ownership of srv directory
      ansible.builtin.file:
        path: "{{ srv_dir }}"
        state: directory
        recurse: yes
        owner: "{{ user_acc }}"
        group: "{{ user_acc }}"
      become: yes

    - name: update app service file
      tags: env
      template:
        src: "{{ app_name }}.service.j2"
        dest: /etc/systemd/system/{{ app_name }}.service
      notify:
        - app daemon reload
        - app restart
      become: yes

    - name: ensure kosa is running
      systemd: name={{ app_name }} state=started enabled=yes
      become: yes

  handlers:
    - name: app daemon reload
      systemd: name={{ app_name }} daemon_reload=yes
      become: yes

    - name: app restart
      systemd: name={{ app_name }} state=restarted daemon_reload=yes
      become: yes

- hosts: app
  remote_user: "{{ user_acc }}"
  vars_files:
    - vars.yml

  tasks:
    - name: Update Caddyfile
      tags: caddy
      template:
        src: "Caddyfile.j2"
        dest: /etc/caddy/Caddyfile
      become: yes
      notify:
        - caddy daemon reload
        - caddy reload

    - name: npm install
      tags: code
      npm:
        path: "{{ app_dir }}"
      become: yes

    - name: stop kosa
      systemd: name={{ app_name }} state=stopped
      become: yes

    - name: install deps, build css / js production assets pipeline
      tags: code
      make:
        chdir: "{{ app_dir }}"
        target: "{{ pre_deploy_target }}"
      become: yes
      become_user: "{{ user_acc }}"

    - name: migrate xtdb database
      tags: code
      make:
        chdir: "{{ app_dir }}"
        target: "{{ migrate_target }}"
      become: yes
      become_user: "{{ user_acc }}"

    - name: start kosa
      systemd: name={{ app_name }} state=started enabled=yes
      become: yes

    - name: Adding the aws access key id in the bashrc file
      lineinfile:
        path: "/root/.bashrc"
        state: present
        line: "export AWS_ACCESS_KEY_ID={{ backup_creds_id }}"
      become: yes

    - name: Adding the aws secret access key in the bashrc file
      lineinfile:
        path: "/root/.bashrc"
        state: present
        line: "export AWS_SECRET_ACCESS_KEY={{ backup_creds_key }}"
      become: yes

    - name: Adding the discord webhook url in the bashrc file
      lineinfile:
        path: "/root/.bashrc"
        state: present
        line: "export DISCORD_WEBHOOK_URL={{ discord_backup_webhook_url }}"
      become: yes

    - name: Create a cron file for backup under /etc/cron.d
      ansible.builtin.cron:
        name: s3 backup
        weekday: "3"
        minute: "0"
        hour: "12"
        user: root
        job: "python3 /srv/kosa-user/kosa/ops/scripts/backups/run.sh"
        cron_file: ansible_s3-backup
      become: yes

    - name: Announce deploy completion to the Discord channel
      community.general.discord:
        webhook_id: "980507364417499146"
        webhook_token: "{{ deploy_discord_webhook_token }}"
        content: "Kosa deploy finished for {{ inventory_hostname }}"

  handlers:
    - name: caddy daemon reload
      systemd: name=caddy daemon_reload=yes
      become: yes

    - name: caddy reload
      systemd: name=caddy state=reloaded daemon_reload=yes
      become: yes
