---
- hosts: app
  remote_user: "{{ user_acc }}"
  vars_files:
    - vars.yml

  tasks:
    - name: stop kosa
      systemd: name={{ app_name }} state=stopped
      become: yes

    - name: clean old txt files
      tags: code
      make:
        chdir: "{{ app_dir }}"
        target: "{{ seed_txt_clean_target }}"
      become: yes
      become_user: "{{ user_acc }}"

    - name: clone txt files from private repo
      tags: code
      environment:
        GIT_SSH_COMMAND: "ssh -i {{ DEPLOY_KEY_PATH }}"
      make:
        chdir: "{{ app_dir }}"
        target: "{{ seed_txt_clone_target }}"
      become: yes
      become_user: "{{ user_acc }}"

    - name: seed (3x looped txt card types) xtdb database
      tags: code
      make:
        chdir: "{{ app_dir }}"
        target: "{{ seed_txt_apply_target }}"
      become: yes
      become_user: "{{ user_acc }}"

    - name: Recursively change ownership of srv directory
      ansible.builtin.file:
        path: "{{ srv_dir }}"
        state: directory
        recurse: yes
        owner: "{{ user_acc }}"
        group: "{{ user_acc }}"
      become: yes

    - name: start kosa
      systemd: name={{ app_name }} state=started enabled=yes
      become: yes
