ansible_conf_dir: "."
user_acc: kosa-user
key_dir: "~/.kosa"
key_name: "kosa_key"
DEPLOY_KEY_PATH: /home/{{ user_acc }}/.ssh/{{ key_name }}

repo_name: kosa
repo_url: https://github.com/pariyatti/{{ repo_name }}.git
repo_remote: origin
repo_version: master

app_name: kosa-app
srv_dir: "/srv/{{ user_acc }}"
repo_dir: "{{ srv_dir }}/{{ repo_name }}"
app_dir: "{{ repo_dir }}"
log_dir: "/var/log/kosa"

env_file: "{{ srv_dir }}/.env"
pre_deploy_target: "init"
migrate_target: "db-migrate-prod"
seed_txt_clean_target: "txt-clean"
seed_txt_clone_target: "txt-clone"
seed_txt_apply_target: "db-txt-prod"

app_env_vars:
  var_name: "var_value"
