---
- hosts: all
  vars_files:
    - vars.yml

  tasks:
    - name: copy priv key to server
      copy:
        src: "{{ ansible_conf_dir }}/{{ key_name }}"
        dest: "{{ DEPLOY_KEY_PATH }}"
        owner: "{{ user_acc }}"
        group: "{{ user_acc }}"
        mode: 0700

    - name: copy pub key to server
      copy:
        src: "{{ ansible_conf_dir }}/{{ key_name }}.pub"
        dest: "{{ DEPLOY_KEY_PATH }}.pub"
        owner: "{{ user_acc }}"
        group: "{{ user_acc }}"
        mode: 0655

    - name: ensure srv directory exists
      file:
        path: "{{ srv_dir }}"
        state: "directory"
        owner: "{{ user_acc }}"
        group: "{{ user_acc }}"
      become: yes

    - name: Clone/pull project repo
      tags: code
      git:
        repo: "{{ repo_url }}"
        version: "{{ repo_version }}"
        dest: "{{ repo_dir }}"
        accept_hostkey: yes
        force: yes
        update: yes
        depth: 1
        key_file: "{{ DEPLOY_KEY_PATH }}"
      notify:
        - app daemon reload
        - app restart

    - name: update environment file
      tags: env
      template:
        src: env.conf.j2
        dest: "{{ env_file }}"
      notify:
        - app daemon reload
        - app restart

    - name: Update app service file
      tags: env
      template:
        src: "{{ app_name }}.service.j2"
        dest: /etc/systemd/system/{{ app_name }}.service
      become: yes
      notify:
        - app daemon reload
        - app restart

    - name: make sure app server is running
      systemd: name={{ app_name }} state=started enabled=yes
      become: yes

  handlers:
    - name: app daemon reload
      systemd: name={{ app_name }} daemon_reload=yes
      become: yes

    - name: app restart
      systemd: name={{ app_name }} state=restarted daemon_reload=yes
      become: yes

- hosts: app
  vars_files:
    - vars.yml

  tasks:
    - name: Update Caddyfile
      tags: caddy
      template:
        src: "Caddyfile.j2"
        dest: /etc/caddy/Caddyfile
      become: yes
      notify:
        - caddy daemon reload
        - caddy reload

    - name: npm install
      tags: code
      npm:
        path: "{{ app_dir }}"

    - name: build css / js production assets pipeline
      tags: code
      command: "{{ pre_deploy_cmd }}"
      args:
        chdir: "{{ app_dir }}"

  handlers:
    - name: caddy daemon reload
      systemd: name=caddy daemon_reload=yes
      become: yes

    - name: caddy reload
      systemd: name=caddy state=reloaded daemon_reload=yes
      become: yes
