name: kosa backend tests

on:
  push:
    branches:
      - master

jobs:
  kosa-tests:
    strategy:
      matrix:
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          lein: 2.9.1

      - name: Check leiningen version
        run: lein version

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          # key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          # key: cljdeps-${{ hashFiles('project.clj') }}
          # key: cljdeps-${{ hashFiles('build.boot') }}
          restore-keys: cljdeps-
      - name: create initial directories
        run: make init-dirs
      - name: install lein deps
        run: make deps
      - name: run kosa tests
        run: make test